#ifndef APPLICATION_CONFIG_H
#define APPLICATION_CONFIG_H

#include <stdbool.h>

/*
 * 这一文件集中保存必须上车实测的参数。烧录后先保持车轮离地，用 t 查看八路
 * 原始值，再修正黑线/背景数组、电机反相和舵机方向；确认后才发送 s。
 */

#define APPLICATION_LEFT_MOTOR_INVERTED (false)
#define APPLICATION_RIGHT_MOTOR_INVERTED (true)
#define APPLICATION_MOTOR_MAXIMUM_OUTPUT (350U)
#define APPLICATION_MOTOR_REVERSAL_DELAY_MS (5U)

#define APPLICATION_DEFAULT_DRIVE_OUTPUT (180)
#define APPLICATION_LEFT_OPEN_LOOP_SCALE (1000U)
#define APPLICATION_RIGHT_OPEN_LOOP_SCALE (1000U)

#define APPLICATION_SERVO_MINIMUM_PULSE_US (1200U)
#define APPLICATION_SERVO_CENTER_PULSE_US (1500U)
#define APPLICATION_SERVO_MAXIMUM_PULSE_US (1800U)
#define APPLICATION_SERVO_INVERTED (false)
#define APPLICATION_MAXIMUM_STEERING_COMMAND (800)

/*
 * 下列数值只是安全启动用的初始标定，必须用本车八路探头在背景和黑线上分别
 * 实测后替换。每个数组从左至右对应 physical[0]～physical[7]。
 */
#define APPLICATION_LINE_CHANNEL_MAP \
    {0U, 1U, 2U, 3U, 4U, 5U, 6U, 7U}
#define APPLICATION_LINE_BACKGROUND_VALUES \
    {3000U, 3000U, 3000U, 3000U, 3000U, 3000U, 3000U, 3000U}
#define APPLICATION_LINE_VALUES \
    {1000U, 1000U, 1000U, 1000U, 1000U, 1000U, 1000U, 1000U}
#define APPLICATION_LINE_POSITION_WEIGHTS \
    {-3500, -2500, -1500, -500, 500, 1500, 2500, 3500}
#define APPLICATION_LINE_MINIMUM_CALIBRATION_RANGE (100U)
#define APPLICATION_LINE_MINIMUM_TOTAL_STRENGTH (300U)

#define APPLICATION_STEERING_KP (0.65f)
#define APPLICATION_STEERING_KI (0.0f)
#define APPLICATION_STEERING_KD (0.0f)
#define APPLICATION_DERIVATIVE_FILTER_COEFFICIENT (0.20f)
#define APPLICATION_MAXIMUM_INVALID_FRAMES (3U)

#endif
